#Specifies each object ID
int64 object_id

#Specifies the minimum angle detected from the polygon
float32 min_angle

#Specifies the maximum angle detected fom the polygon
float32 max_angle

#Time stamp, (could be time timestamp)
time stamp

#Frame ID
string frame_id 

#Specifices if the object is static or dynamic 
bool is_static 

#Time stamp at creation, (could be time timestamp)
time time_created
